-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "REF_programs" (
	"name" text PRIMARY KEY NOT NULL
);
--> statement-breakpoint
ALTER TABLE "REF_programs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "schedules" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "schedules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"owner" uuid NOT NULL,
	"name" text,
	"term" smallint
);
--> statement-breakpoint
ALTER TABLE "schedules" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "terms" (
	"term" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "terms_term_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"start" date NOT NULL,
	"end" date NOT NULL
);
--> statement-breakpoint
ALTER TABLE "terms" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "users" (
	"uid" uuid PRIMARY KEY NOT NULL,
	"idNumber" integer NOT NULL,
	"username" text NOT NULL,
	"displayName" text,
	"major" text,
	"minor" text,
	CONSTRAINT "users_username_key" UNIQUE("username")
);
--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "courses" (
	"courseCode" varchar PRIMARY KEY NOT NULL,
	"fullName" text NOT NULL,
	"units" smallint NOT NULL,
	"academic" boolean DEFAULT true
);
--> statement-breakpoint
ALTER TABLE "courses" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "personalSchedules" (
	"schedule" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name ""personalSchedules_schedule_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"classNumber" bigint NOT NULL,
	CONSTRAINT "personalSchedules_pkey" PRIMARY KEY("schedule","classNumber")
);
--> statement-breakpoint
ALTER TABLE "personalSchedules" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "courseEquivalences" (
	"courseA" varchar NOT NULL,
	"courseB" varchar DEFAULT '' NOT NULL,
	CONSTRAINT "courseEquivalences_pkey" PRIMARY KEY("courseA","courseB")
);
--> statement-breakpoint
ALTER TABLE "courseEquivalences" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "curriculums" (
	"courseCode" varchar NOT NULL,
	"program" text DEFAULT '' NOT NULL,
	CONSTRAINT "curriculums_pkey" PRIMARY KEY("courseCode","program")
);
--> statement-breakpoint
ALTER TABLE "curriculums" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "courseRequisites" (
	"requisite" varchar NOT NULL,
	"incoming" varchar DEFAULT now() NOT NULL,
	"type" varchar NOT NULL,
	CONSTRAINT "courseRequisites_pkey" PRIMARY KEY("requisite","incoming")
);
--> statement-breakpoint
ALTER TABLE "courseRequisites" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "sectionSchedules" (
	"classNumber" bigint NOT NULL,
	"term" smallint NOT NULL,
	"day" varchar[] NOT NULL,
	"start" time,
	"end" time,
	"room" text,
	CONSTRAINT "sectionSchedules_pkey" PRIMARY KEY("classNumber","term","day")
);
--> statement-breakpoint
ALTER TABLE "sectionSchedules" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "sections" (
	"classNumber" bigint NOT NULL,
	"term" smallint NOT NULL,
	"section" text NOT NULL,
	"courseCode" varchar NOT NULL,
	"capacity" smallint NOT NULL,
	"enrolled" smallint NOT NULL,
	"faculty" text,
	"remarks" text,
	CONSTRAINT "sections_pkey" PRIMARY KEY("classNumber","term")
);
--> statement-breakpoint
ALTER TABLE "sections" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "schedules" ADD CONSTRAINT "schedules_owner_fkey" FOREIGN KEY ("owner") REFERENCES "public"."users"("uid") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "schedules" ADD CONSTRAINT "schedules_term_fkey" FOREIGN KEY ("term") REFERENCES "public"."terms"("term") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_major_fkey" FOREIGN KEY ("major") REFERENCES "public"."REF_programs"("name") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_minor_fkey" FOREIGN KEY ("minor") REFERENCES "public"."REF_programs"("name") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "personalSchedules" ADD CONSTRAINT "personalSchedules_schedule_fkey" FOREIGN KEY ("schedule") REFERENCES "public"."schedules"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "courseEquivalences" ADD CONSTRAINT "courseEquivalences_courseA_fkey" FOREIGN KEY ("courseA") REFERENCES "public"."courses"("courseCode") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "courseEquivalences" ADD CONSTRAINT "courseEquivalences_courseB_fkey" FOREIGN KEY ("courseB") REFERENCES "public"."courses"("courseCode") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "curriculums" ADD CONSTRAINT "curriculums_courseCode_fkey" FOREIGN KEY ("courseCode") REFERENCES "public"."courses"("courseCode") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "curriculums" ADD CONSTRAINT "curriculums_program_fkey" FOREIGN KEY ("program") REFERENCES "public"."REF_programs"("name") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "courseRequisites" ADD CONSTRAINT "courseRequisites_requisite_fkey" FOREIGN KEY ("requisite") REFERENCES "public"."courses"("courseCode") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "courseRequisites" ADD CONSTRAINT "courseRequisites_incoming_fkey" FOREIGN KEY ("incoming") REFERENCES "public"."courses"("courseCode") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "sectionSchedules" ADD CONSTRAINT "sectionSchedules_term_classNumber_fkey" FOREIGN KEY ("classNumber","term") REFERENCES "public"."sections"("classNumber","term") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "sections" ADD CONSTRAINT "sections_term_fkey" FOREIGN KEY ("term") REFERENCES "public"."terms"("term") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "sections" ADD CONSTRAINT "sections_courseCode_fkey" FOREIGN KEY ("courseCode") REFERENCES "public"."courses"("courseCode") ON DELETE cascade ON UPDATE cascade;
*/