CREATE TABLE "courses" (
    "courseCode" varchar(7) PRIMARY KEY,
    "fullName" text NOT NULL,
    "units" int NOT NULL,
    "academic" bool DEFAULT true
);
CREATE TABLE "sections" (
    "sectionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "classNumber" numeric(4) NOT NULL,
    "term" numeric(4) NOT NULL,
    "section" varchar NOT NULL,
    "courseCode" varchar(7) NOT NULL,
    "capacity" int NOT NULL,
    "enrolled" int NOT NULL,
    "faculty" text,
    "remarks" text
);
CREATE TABLE "sectionSchedules" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sectionId" int NOT NULL,
    "day" varchar,
    "start" time,
    "end" time,
    "room" text
);
CREATE TABLE "terms" (
    "term" numeric(4) PRIMARY KEY,
    "start" date NOT NULL,
    "end" date NOT NULL
);
CREATE TABLE "users" (
    "uid" uuid PRIMARY KEY,
    "idNumber" int UNIQUE,
    "username" text UNIQUE NOT NULL,
    "displayName" text,
    "major" text,
    "minor" text
);
CREATE TABLE "schedules" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "owner" uuid NOT NULL,
    "name" text,
    "term" numeric(4) NOT NULL
);
CREATE TABLE "personalSchedules" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "schedule" int NOT NULL,
    "sectionId" int NOT NULL
);
CREATE TABLE "REF_programs" ("name" text PRIMARY KEY);
CREATE TABLE "curriculums" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "courseCode" varchar(7) NOT NULL,
    "program" text NOT NULL
);
CREATE TABLE "courseEquivalences" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "courseA" varchar(7) NOT NULL,
    "courseB" varchar(7) NOT NULL
);
CREATE TABLE "courseRequisites" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "requisite" varchar(7) NOT NULL,
    "incoming" varchar(7) NOT NULL,
    "type" varchar(1) NOT NULL
);
ALTER TABLE "courseEquivalences"
ADD FOREIGN KEY ("courseA") REFERENCES "courses" ("courseCode");
ALTER TABLE "courseEquivalences"
ADD FOREIGN KEY ("courseB") REFERENCES "courses" ("courseCode");
ALTER TABLE "courseRequisites"
ADD FOREIGN KEY ("requisite") REFERENCES "courses" ("courseCode");
ALTER TABLE "courseRequisites"
ADD FOREIGN KEY ("incoming") REFERENCES "courses" ("courseCode");
ALTER TABLE "curriculums"
ADD FOREIGN KEY ("program") REFERENCES "REF_programs" ("name");
ALTER TABLE "curriculums"
ADD FOREIGN KEY ("courseCode") REFERENCES "courses" ("courseCode");
ALTER TABLE "users"
ADD FOREIGN KEY ("major") REFERENCES "REF_programs" ("name");
ALTER TABLE "users"
ADD FOREIGN KEY ("minor") REFERENCES "REF_programs" ("name");
ALTER TABLE "personalSchedules"
ADD FOREIGN KEY ("schedule") REFERENCES "schedules" ("id");
ALTER TABLE "personalSchedules"
ADD FOREIGN KEY ("sectionId") REFERENCES "sections" ("sectionId");
ALTER TABLE "schedules"
ADD FOREIGN KEY ("term") REFERENCES "terms" ("term");
ALTER TABLE "schedules"
ADD FOREIGN KEY ("owner") REFERENCES "users" ("uid");
ALTER TABLE "sections"
ADD FOREIGN KEY ("courseCode") REFERENCES "courses" ("courseCode");
ALTER TABLE "sectionSchedules"
ADD FOREIGN KEY ("sectionId") REFERENCES "sections" ("sectionId");