alter table "public"."courseEquivalences" drop constraint "courseEquivalences_courseA_fkey";

alter table "public"."courseEquivalences" drop constraint "courseEquivalences_courseB_fkey";

alter table "public"."curriculums" drop constraint "curriculums_courseCode_fkey";

alter table "public"."personalSchedules" drop constraint "personalSchedules_sectionId_fkey";

alter table "public"."sectionSchedules" drop constraint "sectionSchedules_sectionId_fkey";

alter table "public"."sections" drop constraint "sections_courseCode_fkey";

alter table "public"."courseRequisites" drop constraint "courseRequisites_incoming_fkey";

alter table "public"."courseRequisites" drop constraint "courseRequisites_requisite_fkey";

alter table "public"."users" drop constraint "users_idNumber_key";

alter table "public"."courses" drop constraint "courses_pkey";

alter table "public"."sections" drop constraint "sections_pkey";

drop index if exists "public"."courses_pkey";

drop index if exists "public"."sections_pkey";

drop index if exists "public"."users_idNumber_key";

alter table "public"."courseEquivalences" drop column "courseA";

alter table "public"."courseEquivalences" drop column "courseB";

alter table "public"."courseEquivalences" add column "coursea" character varying(7) not null;

alter table "public"."courseEquivalences" add column "courseb" character varying(7) not null;

alter table "public"."courses" drop column "courseCode";

alter table "public"."courses" drop column "fullName";

alter table "public"."courses" add column "course_code" character varying(7) not null;

alter table "public"."courses" add column "full_name" text;

alter table "public"."curriculums" drop column "courseCode";

alter table "public"."curriculums" add column "course_code" character varying(7) not null;

alter table "public"."personalSchedules" drop column "sectionId";

alter table "public"."personalSchedules" add column "section_id" integer not null;

alter table "public"."sectionSchedules" drop column "sectionId";

alter table "public"."sectionSchedules" add column "section_id" integer not null;

alter table "public"."sections" drop column "classNumber";

alter table "public"."sections" drop column "courseCode";

alter table "public"."sections" drop column "sectionId";

alter table "public"."sections" add column "class_number" numeric(4,0) not null;

alter table "public"."sections" add column "course_code" character varying(7) not null;

alter table "public"."sections" add column "id" integer generated by default as identity not null;

alter table "public"."users" drop column "displayName";

alter table "public"."users" drop column "idNumber";

alter table "public"."users" add column "display_name" text;

alter table "public"."users" add column "id_number" numeric(8,0);

CREATE UNIQUE INDEX courses_pkey ON public.courses USING btree (course_code);

CREATE UNIQUE INDEX sections_pkey ON public.sections USING btree (id);

CREATE UNIQUE INDEX "users_idNumber_key" ON public.users USING btree (id_number);

alter table "public"."courses" add constraint "courses_pkey" PRIMARY KEY using index "courses_pkey";

alter table "public"."sections" add constraint "sections_pkey" PRIMARY KEY using index "sections_pkey";

alter table "public"."courseEquivalences" add constraint "courseEquivalences_coursea_fkey" FOREIGN KEY (coursea) REFERENCES courses(course_code) not valid;

alter table "public"."courseEquivalences" validate constraint "courseEquivalences_coursea_fkey";

alter table "public"."courseEquivalences" add constraint "courseEquivalences_courseb_fkey" FOREIGN KEY (courseb) REFERENCES courses(course_code) not valid;

alter table "public"."courseEquivalences" validate constraint "courseEquivalences_courseb_fkey";

alter table "public"."curriculums" add constraint "curriculums_course_code_fkey" FOREIGN KEY (course_code) REFERENCES courses(course_code) not valid;

alter table "public"."curriculums" validate constraint "curriculums_course_code_fkey";

alter table "public"."personalSchedules" add constraint "personalSchedules_section_id_fkey" FOREIGN KEY (section_id) REFERENCES sections(id) not valid;

alter table "public"."personalSchedules" validate constraint "personalSchedules_section_id_fkey";

alter table "public"."sectionSchedules" add constraint "sectionSchedules_section_id_fkey" FOREIGN KEY (section_id) REFERENCES sections(id) not valid;

alter table "public"."sectionSchedules" validate constraint "sectionSchedules_section_id_fkey";

alter table "public"."sections" add constraint "sections_course_code_fkey" FOREIGN KEY (course_code) REFERENCES courses(course_code) not valid;

alter table "public"."sections" validate constraint "sections_course_code_fkey";

alter table "public"."courseRequisites" add constraint "courseRequisites_incoming_fkey" FOREIGN KEY (incoming) REFERENCES courses(course_code) not valid;

alter table "public"."courseRequisites" validate constraint "courseRequisites_incoming_fkey";

alter table "public"."courseRequisites" add constraint "courseRequisites_requisite_fkey" FOREIGN KEY (requisite) REFERENCES courses(course_code) not valid;

alter table "public"."courseRequisites" validate constraint "courseRequisites_requisite_fkey";

alter table "public"."users" add constraint "users_idNumber_key" UNIQUE using index "users_idNumber_key";


